# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_celebrate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogCelebrate(object):
    def setupUi(self, DialogCelebrate):
        DialogCelebrate.setObjectName("DialogCelebrate")
        DialogCelebrate.resize(450, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogCelebrate.setWindowIcon(icon)
        self.label_celebrate = QtWidgets.QLabel(DialogCelebrate)
        self.label_celebrate.setGeometry(QtCore.QRect(0, 0, 450, 200))
        self.label_celebrate.setStyleSheet("")
        self.label_celebrate.setText("")
        self.label_celebrate.setObjectName("label_celebrate")

        self.retranslateUi(DialogCelebrate)
        QtCore.QMetaObject.connectSlotsByName(DialogCelebrate)

    def retranslateUi(self, DialogCelebrate):
        _translate = QtCore.QCoreApplication.translate
        DialogCelebrate.setWindowTitle(_translate("DialogCelebrate", "欧爷"))
from . import resource_rc
