# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_help.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogHelp(object):
    def setupUi(self, DialogHelp):
        DialogHelp.setObjectName("DialogHelp")
        DialogHelp.resize(600, 600)
        DialogHelp.setMinimumSize(QtCore.QSize(600, 600))
        DialogHelp.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogHelp.setWindowIcon(icon)
        DialogHelp.setModal(False)
        self.gridFrame = QtWidgets.QFrame(DialogHelp)
        self.gridFrame.setGeometry(QtCore.QRect(0, 0, 600, 50))
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setContentsMargins(10, 10, 10, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_top = QtWidgets.QLabel(self.gridFrame)
        self.label_top.setText("")
        self.label_top.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_top.setObjectName("label_top")
        self.gridLayout.addWidget(self.label_top, 0, 1, 1, 1)
        self.gridFrame_2 = QtWidgets.QFrame(DialogHelp)
        self.gridFrame_2.setGeometry(QtCore.QRect(0, 50, 300, 550))
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_2.setContentsMargins(5, 1, 5, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_left = QtWidgets.QLabel(self.gridFrame_2)
        self.label_left.setText("")
        self.label_left.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_left.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_left.setWordWrap(True)
        self.label_left.setObjectName("label_left")
        self.gridLayout_2.addWidget(self.label_left, 0, 0, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(DialogHelp)
        self.gridFrame_3.setGeometry(QtCore.QRect(300, 50, 300, 550))
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_right = QtWidgets.QLabel(self.gridFrame_3)
        self.label_right.setText("")
        self.label_right.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_right.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_right.setWordWrap(True)
        self.label_right.setObjectName("label_right")
        self.gridLayout_3.addWidget(self.label_right, 0, 0, 1, 1)

        self.retranslateUi(DialogHelp)
        QtCore.QMetaObject.connectSlotsByName(DialogHelp)

    def retranslateUi(self, DialogHelp):
        _translate = QtCore.QCoreApplication.translate
        DialogHelp.setWindowTitle(_translate("DialogHelp", "帮助"))
from . import resource_rc
