# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_window_cover.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import qlabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(0, 0, 800, 400))
        self.gridFrame.setMinimumSize(QtCore.QSize(800, 400))
        self.gridFrame.setMaximumSize(QtCore.QSize(800, 400))
        self.gridFrame.setStyleSheet("background-image: url(:/image/image/cover.jpg);")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame1.setGeometry(QtCore.QRect(0, 400, 800, 200))
        self.gridFrame1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.gridFrame1.setObjectName("gridFrame1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_about = qlabel.QLabel(self.gridFrame1)
        self.label_about.setMinimumSize(QtCore.QSize(266, 200))
        self.label_about.setMaximumSize(QtCore.QSize(266, 200))
        self.label_about.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_about.setStyleSheet("background-image: url(:/image/image/about.jpg);")
        self.label_about.setLineWidth(0)
        self.label_about.setText("")
        self.label_about.setObjectName("label_about")
        self.gridLayout_2.addWidget(self.label_about, 0, 3, 1, 1)
        self.label_help = qlabel.QLabel(self.gridFrame1)
        self.label_help.setMinimumSize(QtCore.QSize(266, 200))
        self.label_help.setMaximumSize(QtCore.QSize(266, 200))
        self.label_help.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_help.setStyleSheet("background-image: url(:/image/image/help.jpg);")
        self.label_help.setText("")
        self.label_help.setOpenExternalLinks(True)
        self.label_help.setObjectName("label_help")
        self.gridLayout_2.addWidget(self.label_help, 0, 0, 1, 1)
        self.label_start = qlabel.QLabel(self.gridFrame1)
        self.label_start.setMinimumSize(QtCore.QSize(268, 200))
        self.label_start.setMaximumSize(QtCore.QSize(268, 200))
        self.label_start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_start.setMouseTracking(False)
        self.label_start.setStyleSheet("background-image: url(:/image/image/start.jpg);")
        self.label_start.setText("")
        self.label_start.setObjectName("label_start")
        self.gridLayout_2.addWidget(self.label_start, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "秒"))
from . import resource_rc
